### ISSUE TITLE
Logs from recaptcha__en.js: "Cannot read property 'style' of null""

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [sarneeh/reaptcha#218] opened 2021-08-20 00:24 UTC
We are using  "reaptcha": "^1.5.0", 
and see in logs (but not able to reproduce locally) intermittent messages 
"Cannot read property 'style' of null" 
 at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/ecapuzyywmdXQ5gJHS3JQiXe/recaptcha__en.js:11:478)
Release part of url  and particular positions can be different.

The issue is similar to reported at  [ dozoisch/react-google-recaptcha Cannot read property 'style' of null #129](https://github.com/dozoisch/react-google-recaptcha/issues/129) and  [Auth error only after recaptcha: "Cannot read property 'style' of null" #3356](https://github.com/firebase/firebase-js-sdk/issues/3356)

According to a few comments, the error doesn't seem to have any effect and can be ignored, but it will be good to suppress it if possible.

Could you please provide  your suggestions.

One of the suggestion in other threads  was 

> worked for me is setting a timeout before resetting the recaptcha
> setTimeout(() => recaptchaRef.current.reset(), 500);
> From <https://github.com/dozoisch/react-google-recaptcha/issues/129

>

**Comment by sarneeh** [comment] 2021-09-03 09:23
Without any steps to reproduce this issue I can't really do anything about this. Can you provide an example or steps to reproduce this issue?

**Comment by YouZag** [comment] 2021-09-09 12:34
The above referenced issue describes the steps very well just a few comments up.  I'm at a position where my app is also unusable due to this error. Unfortunately for my implementation the error breaks the login.  It only occurs for me when an invisible captcha requires picture identifying verification.

**Comment by sarneeh** [comment] 2022-03-18 10:51
Investigated this issue and I didn't found any other workaround than `setTimeout(() => recaptchaRef.current.reset(), 500)` which supresses the error with success (but adds unnecessary delay on reset).

Also, I don't want to put this workaround code into the library as this is a bug of Google Recaptcha script and that's where it should be fixed.

What I'd propose is to ignore this specific error in your error reporting software as it doesn't break any functionality.

**Closed by sarneeh** 2022-03-18 10:51 UTC
Labels: bug
